name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: self-hosted
    steps:
      - name: Check Out Sources
        uses: actions/checkout@v4   
      - name: Install NPM Dependencies
        run: npm install
      - name: Run Build
        run: npm run build  