name: bubuild CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Check Out Sources
        uses: actions/checkout@v4    
      - name: Install NPM Dependencies
        run: npm install
      - name: Run Build
        run: npm run build  
      - name: Configure npm repository
        run: .ci/setup-npm-repo

      - name: Publish
        run: npm publish